services:
  app:
    build: .
    container_name: emp_asset_backend

    ports:
      - "8000:8000"

    env_file:
      - .env

    volumes:
      - .:/app

    depends_on:
      - db

    command: >
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:17

    container_name: emp_asset_postgres

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Mridul123
      POSTGRES_DB: employee_asset_management

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: