"""initial migration 

Revision ID: 1bf451c32463
Revises: 
Create Date: 2026-07-13 18:25:00.193685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1bf451c32463'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employees')
    op.drop_table('assets')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('asset_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('asset_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('asset_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('brand', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('employee_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('assigned_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('returned_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], name=op.f('assets_employee_id_fkey')),
    sa.PrimaryKeyConstraint('asset_id', name=op.f('assets_pkey')),
    sa.UniqueConstraint('asset_code', name=op.f('assets_asset_code_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('employees',
    sa.Column('employee_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('employee_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('employee_age', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('employee_gender', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('employee_email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('employee_post', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('department', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('years_of_experience', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('joining_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('employee_id', name=op.f('employees_pkey')),
    sa.UniqueConstraint('employee_email', name=op.f('employees_employee_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
