"""Initial migration

Revision ID: ccee11214d2d
Revises: 
Create Date: 2026-07-14 12:16:23.113215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccee11214d2d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('employee_name', sa.String(), nullable=False),
    sa.Column('employee_age', sa.String(), nullable=False),
    sa.Column('employee_gender', sa.String(), nullable=False),
    sa.Column('employee_email', sa.String(), nullable=False),
    sa.Column('employee_post', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('years_of_experience', sa.String(), nullable=True),
    sa.Column('joining_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('employee_id'),
    sa.UniqueConstraint('employee_email')
    )
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('assets',
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('asset_code', sa.String(), nullable=False),
    sa.Column('asset_name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('returned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.PrimaryKeyConstraint('asset_id'),
    sa.UniqueConstraint('asset_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assets')
    op.drop_table('users')
    op.drop_table('employees')
    # ### end Alembic commands ###
